### ISSUE TITLE
pralemz

### ISSUE THREAD

**Issue by naina726** [naina726/Wiki#1]
Problem with placement of logout form in code, problem with format of search bar, problem displaying one part of content in editform - not displaying results, both of these are very straightforward questions but it is very unclear to me how to resolve, i have trial-and-errored both on everything i can think of and i cant fix it @DBrodsky90 @WilliamfShaw @awongh @pavankat

**Comment by WilliamfShaw** [comment]
We need more info. Look back at the last project and resubmit the issue with the proper format please! Thanks :hamster:

**Comment by naina726** [comment]
honestly im just lost in my own code and dont know what to do
